/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mc_varnam_VarnamInitLib */

#ifndef _Included_com_mc_varnam_VarnamInitLib
#define _Included_com_mc_varnam_VarnamInitLib
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_mc_varnam_VarnamInitLib_varnam_init
  (JNIEnv *, jclass, jchar *, varnam **, jchar **);
#ifdef __cplusplus
}
#endif
#endif
